name: worddle
version: '1.0'
summary: Guess a five-letter word in siz attempts
description: |
  Wordle is a web-based word game developed by Josh Wardle. Players have six attempts to guess a five-letter word; feedback is given for each guess, in the form of colored tiles, indicating when letters match or occupy the correct position. 

grade: stable
confinement: strict
icon: snap/gui/icon.png
base: core20
compression: lzo

architectures:
  - build-on: amd64
    run-on: amd64

environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/qt5-core20

apps:
  worddle:
    command: /usr/bin/worddle
    desktop: usr/share/applications/worddle.desktop
    plugs:
        - browser-support
        - desktop
        - desktop-legacy
        - gsettings
        - home
        - opengl
        - audio-playback
        - unity7
        - x11
        - network
        - wayland

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  qt5-core20:
    interface: content
    target: $SNAP/qt5-core20
    default-provider: qt5-core20

parts:
   build-src:
     plugin: qmake
     build-packages:
       - build-essential
       - qtbase5-dev
       - qttools5-dev
       - qtwebengine5-dev
     source: https://github.com/keshavbhatt/worddle.git
     source-subdir: src/
     override-build: |
            snapcraftctl build
            sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/src/worddle.desktop
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications
            cp -rf ${SNAPCRAFT_PART_SRC}/src/worddle.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/worddle.desktop
   snap-launcher:
     plugin: dump
     source-type: local
     source: snap_launcher/
     after: [build-src]
